#numpy

In [1]:
import numpy as np

In [12]:
myarr = np.array([[2,4,55,6]], np.int8)

**np.int8 shows integer is of 8 bit**

In [13]:
myarr

array([[ 2,  4, 55,  6]], dtype=int8)

In [14]:
myarr[0,1]

4

In [15]:
myarr.shape

(1, 4)

In [16]:
myarr.dtype

dtype('int8')

In [18]:
myarr[0,1]=35


#Array creation: conversion from other Python structure

In [19]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [20]:
listarray.dtype

dtype('int32')

In [21]:
listarray.shape

(3, 3)

In [22]:
listarray.size

9

In [23]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [24]:
zeros= np.zeros((2,5))

In [25]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
zeros.dtype


dtype('float64')

In [27]:
zeros.shape

(2, 5)

In [30]:
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
lspace=np.linspace(1,5,12)


In [34]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [35]:
emp = np.empty((4,6))
emp

array([[6.23042070e-307, 3.56043053e-307, 1.60219306e-306,
        7.56571288e-307, 1.89146896e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
       [2.22522597e-306, 1.33511018e-306, 6.23057689e-307,
        1.86921279e-306, 8.90098127e-307, 1.78020848e-306],
       [1.60219035e-306, 1.42418172e-306, 2.04712906e-306,
        7.56589622e-307, 1.11258277e-307, 8.90111708e-307]])

In [37]:
emp_like = np.empty_like(lspace)
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [38]:
ide = np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [39]:
ide.shape

(45, 45)

In [41]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [43]:
arr=arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [45]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [46]:
arr.shape

(99,)

In [48]:
x= [[1,2,3],[4,5,6],[7,1,0]]
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [49]:
ar.sum(axis=0)

array([12,  8,  9])

In [50]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [51]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [54]:
#ar.flat
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [55]:
ar.ndim

2

In [56]:
ar.size

9

In [57]:
ar.nbytes

36

In [60]:

one = np.array([1,2,3,4])
one.argmax()

3

In [61]:
one.argmin()

0

In [62]:
one.argsort()

array([0, 1, 2, 3], dtype=int64)

In [63]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [64]:
ar.argmin()

8

In [66]:
ar.argmax()

6

In [67]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [68]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [69]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [70]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [71]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [74]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [75]:
ar2=np.array([[1,2,1],[4,0,6],[8,1,0]])

In [76]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [77]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [78]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [79]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [80]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [82]:
ar.sum()

29

In [83]:
ar.max()

7

In [84]:
ar.min()

0

In [85]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [86]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [87]:
type(np.where(ar>5))

tuple

In [88]:
np.count_nonzero(ar)

8

In [90]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [91]:
ar[1,2]=0

In [92]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [93]:
import sys
py_ar= [0,4,55,2]
np_ar=np.array(py_ar)

In [94]:
sys.getsizeof(1) *len(py_ar)

112

In [95]:
np_ar.itemsize * np_ar.size

16